apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: order-processor

build:
  tagPolicy:
    inputDigest: { }
  artifacts:
    - image: bibryam/order-processor
      docker:
        dockerfile: Dockerfile
  local: {}

manifests:
  rawYaml:
    - deploy/*

deploy:
  kubectl: {}
  logs:
    prefix: auto

portForward:
  - resourceType: deployment
    resourceName: order-processor
    port: 5002
    localPort: 5002
  - resourceType: deployment
    resourceName: order-processor
    port: 9090
    localPort: 5012
  - resourceType: deployment
    resourceName: order-processor
    port: 3500
    localPort: 3502