apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkout
  name: checkout
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: checkout
  type: LoadBalancer
