apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      annotations:
        dapr.io/app-id: "order-processor"
        dapr.io/enabled: "true"
        dapr.io/app-port: "5002"
        dapr.io/metrics-port: "9090"
        dapr.io/log-level: "info"
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: bibryam/order-processor
          ports:
            - containerPort: 5002
